export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';

export const GET_USER_GITHUB = 'GET_USER_GITHUB';
export const GET_USER_REPOS = 'GET_USER_REPOS';